Log cleanup cronjob
devgeniem/wp-oopi pull request #16
Opened 2021-10-29 10:19 UTC by HPiirainen

The MySQL query cleaning the table is quite complicated, but it allows maintaning full rollback support by removing all but the newest `OK` entry from the log versus simply removing all rows older that X days.

The cronjob assumes the log table is using the new DB structure from `1.0.0` update (`post_id` column renamed to `wp_id` in log table).

As a note however, the plugin does not include a migration to make that change, so basically the cronjob only works if

* the site has installed `1.0.0` without having an earlier version
* the column name is changed manually (for pre-1.0.0 version)
* the log table is deleted manually and plugin is re-activated (pre-1.0.0 versions).

2021-10-30 04:32 UTC, ironland requested changes
Pari kysymystä. Vaihdetaan approveksi, jos vastaukset niihin. Ei tarvitse muutella välttämättä mitään.

2021-10-30 04:32 UTC, ironland commented on src/CronJobs.php
> +            $interval  = Settings::get( "cron_interval_$key" );
Tarviiko tässä interpolaatio-sulkeet muuttujan ympärille? `{}`

2021-10-30 04:32 UTC, ironland commented on src/CronJobs.php
> +                \wp_schedule_event( time(), $interval, $job::HOOK );
Kannattaa vielä tarkistaa, onko `time()` -metodin palauttama oikea, vai heittääkö aikavyöhykkeen verran. Vai onko sillä tässä edes sen suurempaa merkitystäkään?

2021-10-30 04:32 UTC, ironland commented on src/LogCleaner.php
> +            JOIN (
Kannattaa vielä varuiksi käyttää tää sql-query tsekissä vaikka juhanilla, jos jaksat. 👍

2021-11-19 09:50 UTC, HPiirainen commented on src/CronJobs.php
> +                \wp_schedule_event( time(), $interval, $job::HOOK );
Täällä on kaikissa esimerkeissä käytetty `time()`: https://developer.wordpress.org/reference/functions/wp_schedule_event/#user-contributed-notes

Mutta tolla ei siis ole isompaa merkitystä, tärkeämpi on `$interval`, että se ajaa tietyllä syklillä tota cronia.

2021-11-19 09:52 UTC, HPiirainen commented on src/CronJobs.php
> +            $interval  = Settings::get( "cron_interval_$key" );
Fixed, luettavuuden kannalta hyvä olla.

2021-11-29 19:43 UTC, ironland approved these changes

2022-01-24 11:33 UTC, HPiirainen commented
Suljetaan PR tältä erää, OOPIn rollback ei todennäköisesti toimi oikein, joten näin monimutkaista SQL-queryä ei silloin tarvittaisi. Tehdään uusi versio, jossa kevyempi siivous-SQL.

2022-01-24 11:33 UTC, closed without merging